import { KundliResultLayout } from '@/expt/KundliResultLayout'

export function AboutPage() {
  return (
    <KundliResultLayout>
      <div className="mx-auto max-w-2xl px-4 py-8 text-foreground">
        <h1 className="mb-6 text-3xl font-bold tracking-tight">About the Project</h1>
        <p className="mb-4 text-muted-foreground leading-relaxed">
          Klimate Kundli is an interactive art exhibition and scientific exploration that maps climate data to personal horoscopes.
        </p>
        <p className="text-muted-foreground leading-relaxed">
          By combining birth year and location with historical emissions and temperature anomalies, the project visualizes our personal astrological alignment with the changing climate of the planet.
        </p>
      </div>
    </KundliResultLayout>
  )
}

export function PrivacyPage() {
  return (
    <KundliResultLayout>
      <div className="mx-auto max-w-2xl px-4 py-8 text-foreground">
        <h1 className="mb-6 text-3xl font-bold tracking-tight">Privacy Policy</h1>
        <p className="mb-4 text-muted-foreground leading-relaxed">
          Your privacy is important to us. Any information you enter (birth year, birth city, and lived cities) is processed locally on your device or sent to our caching APIs to compute climate cards.
        </p>
        <p className="text-muted-foreground leading-relaxed">
          We do not sell, rent, or store your personal identifiers. Generated climate horoscopes are stored anonymously and can be accessed by their unique slug.
        </p>
      </div>
    </KundliResultLayout>
  )
}

export function DisclaimerPage() {
  return (
    <KundliResultLayout>
      <div className="mx-auto max-w-2xl px-4 py-8 text-foreground">
        <h1 className="mb-6 text-3xl font-bold tracking-tight">Disclaimer</h1>
        <p className="mb-4 text-muted-foreground leading-relaxed">
          The horoscopes generated by this tool are for educational, artistic, and speculative purposes only. While we use real historical climate data from Open-Meteo, OWID, and IMD, these horoscopes do not constitute scientific forecasts or actual astrological advice.
        </p>
      </div>
    </KundliResultLayout>
  )
}

export function KlimateTwinPage() {
  return (
    <KundliResultLayout>
      <div className="mx-auto max-w-2xl px-4 py-8 text-foreground">
        <h1 className="mb-6 text-3xl font-bold tracking-tight">Find Your Climate Twin</h1>
        <p className="mb-4 text-muted-foreground leading-relaxed">
          This feature will allow you to find others who share similar climate signatures or lived experiences across space and time.
        </p>
        <p className="text-muted-foreground leading-relaxed font-semibold">
          Coming soon!
        </p>
      </div>
    </KundliResultLayout>
  )
}
